# Generated by Django 2.2.1 on 2020-08-22 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_to_do_app', '0003_auto_20200822_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='isDone',
        ),
    ]
